### ISSUE TITLE
Configuration file is not optional

### ISSUE THREAD

**Issue by michele-brambilla** [ess-dmsc/just-bin-it#40]
According to the documentation `configuration file` is an option parameter, but
```shell
python bin/just-bin-it.py -b ess01:9092 -t INSTRUMENT_histCommands -rt INSTRUMENT_histResponse
```
gives
```shell
  File "bin/just-bin-it.py", line 35
    raise Exception(f"Could not load configuration file {file}") from error
```

**Comment by mattclarke** [comment]
I cannot reproduce this; I am using `-b localhost:9092 -t hist_commands -rt hist_responses` and that works fine
What file did the exception say it was trying to load?

**Comment by michele-brambilla** [comment]
I don't know what went wrong yesterday. Now it's working. I close the issue.
